_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/rl/ppo_drew.py
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 49
                - 55
            "2":
                - 1
                - 49
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
anneal_lr:
    value: false
batch_size:
    value: 200
capture_video:
    value: true
checkpoint:
    value: null
clip_coef:
    value: 0.2
clip_vloss:
    value: false
control_mode:
    value: pd_joint_delta_pos
cuda:
    value: true
ent_coef:
    value: 0
env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 200
        env_id: PlaySoccer-v1
        num_envs: 4
        obs_mode: state
        partial_reset: true
        render_mode: rgb_array
        reward_mode: normalized_dense
        sim_backend: gpu
env_id:
    value: PlaySoccer-v1
eval_env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 200
        env_id: PlaySoccer-v1
        num_envs: 16
        obs_mode: state
        partial_reset: false
        render_mode: rgb_array
        reward_mode: normalized_dense
        sim_backend: gpu
eval_freq:
    value: 25
eval_partial_reset:
    value: false
eval_reconfiguration_freq:
    value: 1
evaluate:
    value: false
exp_name:
    value: custom-ppo-Socker-v1-
finite_horizon_gae:
    value: true
gae_lambda:
    value: 0.9
gamma:
    value: 0.8
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 25
norm_adv:
    value: true
num_envs:
    value: 4
num_eval_envs:
    value: 16
num_eval_steps:
    value: 50
num_iterations:
    value: 250000
num_minibatches:
    value: 8
num_steps:
    value: 50
partial_reset:
    value: true
reconfiguration_freq:
    value: null
reward_scale:
    value: 1
save_model:
    value: true
save_train_video_freq:
    value: null
seed:
    value: 3141
target_kl:
    value: 0.1
torch_deterministic:
    value: true
total_timesteps:
    value: 50000000
track:
    value: true
update_epochs:
    value: 8
vf_coef:
    value: 0.5
wandb_entity:
    value: stonet2000
wandb_project_name:
    value: ManiSkill
